### ISSUE TITLE
与microsoft office软件好像有兼容性问题

### ISSUE THREAD

**Issue by Cansiny0320** [mydockfinder/mydockfinder#104]
win10系统版本 21H1

软件版本：v5.9.9.86

打开 word 和 ppt 后会非常的卡，甚至直接卡死（只有 word 和 ptt 里面卡，其他软件依然正常）

关闭dock后，word 和 ptt 的表现恢复正常

**Comment by mydockfinder** [comment]
office版本多少




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 下午5:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] 与microsoft office软件好像有兼容性问题 (#104)





 
win10系统版本 21H1
 
软件版本：v5.9.9.86
 
打开 word 和 ppt 后会非常的卡，甚至直接卡死（只有 word 和 ptt 里面卡，其他软件依然正常）
 
关闭dock后，word 和 ptt 的表现恢复正常

**Comment by Cansiny0320** [comment]
哦弄错了 好像是2019版

**Comment by Cansiny0320** [comment]
> office版本多少
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder" ***@***.***&gt;; 发送时间:&nbsp;2021年6月24日(星期四) 下午5:08 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder] 与microsoft office软件好像有兼容性问题 (#104) win10系统版本 21H1 软件版本：v5.9.9.86 打开 word 和 ppt 后会非常的卡，甚至直接卡死（只有 word 和 ptt 里面卡，其他软件依然正常） 关闭dock后，word 和 ptt 的表现恢复正常 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

2019版

**Comment by mydockfinder** [comment]
不应该啊，我也是2019，不卡啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 下午5:42
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 与microsoft office软件好像有兼容性问题 (#104)





  
office版本多少
 …
 ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder" @.&gt;; 发送时间: 2021年6月24日(星期四) 下午5:08 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder] 与microsoft office软件好像有兼容性问题 (#104) win10系统版本 21H1 软件版本：v5.9.9.86 打开 word 和 ppt 后会非常的卡，甚至直接卡死（只有 word 和 ptt 里面卡，其他软件依然正常） 关闭dock后，word 和 ptt 的表现恢复正常 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
2019版
 
&mdash;

**Comment by Cansiny0320** [comment]
不清楚为什么 我发现用管理员模式 启动 word 的话会好一点 没那么卡，正常启动光标都不会闪 直接卡死

**Comment by mydockfinder** [comment]
你试试 dock word图标右键&nbsp; 不再显示此程序最小化动画，然后重写打开word试试&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 晚上8:37
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 与microsoft office软件好像有兼容性问题 (#104)





 
不清除为什么 我发现用管理员模式 启动 word 的话会好一点 没那么卡，正常启动光标都不会闪 直接卡死
 
&mdash;

**Comment by Cansiny0320** [comment]
有效果，至少打开word之后能操作了 但还是有卡顿的情况

**Comment by mydockfinder** [comment]
那你试试dock设置关闭全局模糊效果



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 晚上8:47
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] 与microsoft office软件好像有兼容性问题 (#104)





 
有效果，至少打开word之后能操作了 但还是有卡顿的情况
 
&mdash;

**Comment by Cansiny0320** [comment]
这个没什么效果 卡顿的表现就是键盘输入和鼠标点击都有明显的延迟

**Comment by Cansiny0320** [comment]
重装了一遍office居然好了 可能是windows自己的问题
