### ISSUE TITLE
Pr Au 记事本的最大化沉浸取色似乎不正确

### ISSUE THREAD

**Issue by Miuzarte** [mydockfinder/mydockfinder#145]
![image](https://user-images.githubusercontent.com/66856838/124551994-85a24700-de65-11eb-8127-7ae7413b7040.png)
![image](https://user-images.githubusercontent.com/66856838/124552096-a5396f80-de65-11eb-9687-b8d868fc866d.png)
![image](https://user-images.githubusercontent.com/66856838/124552353-006b6200-de66-11eb-916b-ebee733c0cd7.png)

**Comment by mydockfinder** [comment]
新版的不是取色，你是不是没开标题栏跟随系统变色，新版的沉浸模式是系统标题栏窗口会变成系统的DWM全局颜色




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 下午2:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder] Pr Au的最大化沉浸取色似乎不正确 (#145)

**Comment by Miuzarte** [comment]
> 新版的不是取色，你是不是没开标题栏跟随系统变色，新版的沉浸模式是系统标题栏窗口会变成系统的DWM全局颜色
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder" ***@***.***&gt;; 发送时间:&nbsp;2021年7月6日(星期二) 下午2:23 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder] Pr Au的最大化沉浸取色似乎不正确 (#145) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

确实没开标题栏变色  因为不喜欢
可是资源管理器的沉浸是正常的, 这是特意的吗

**Comment by mydockfinder** [comment]
倒不是，主要是能不用模糊就不用模糊，太费GPU了，我下次加个监测就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 下午3:25
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Pr Au 记事本的最大化沉浸取色似乎不正确 (#145)





  
新版的不是取色，你是不是没开标题栏跟随系统变色，新版的沉浸模式是系统标题栏窗口会变成系统的DWM全局颜色
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder" @.&gt;; 发送时间:&nbsp;2021年7月6日(星期二) 下午2:23 @.&gt;; @.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder] Pr Au的最大化沉浸取色似乎不正确 (#145) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
确实没开标题栏变色  因为不喜欢
 可是资源管理器的沉浸是正常的, 这是特意的吗
