### ISSUE TITLE
request: change "MEN" to "MEM" in English translation

### ISSUE THREAD

**Issue by twonth** [mydockfinder/mydockfinder#174]
The letters "MEM" make more sense for the "memory monitor" in the top bar than "MEN". 
![image](https://user-images.githubusercontent.com/6320070/127783427-bfae45f2-d14f-4129-986d-6751b503479c.png)

Thank you for all your work on this great software!

**Comment by VladCarlsson** [comment]
This can be easily edited in the translation file but as far as I noticed, it resets every time a new update is released and applied. I love this so much, I hope the notifications can improve in the future, otherwise, it's amazing <3

**Comment by mydockfinder** [comment]
这几个CPU内存监控是仿照mac里面的istat menu做的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月2日(星期一) 凌晨4:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] request: change &quot;MEN&quot; to &quot;MEM&quot; in English translation (#174)





 
This can be easily edited in the translation file but as far as I noticed, it resets every time a new update is released and applied. I love this so much, I hope the notifications can improve in the future, otherwise, it's amazing <3
 
&mdash;

**Comment by twonth** [comment]
Thank you for the reply!

I believe iStat says "MEM" and not "MEN":
![image](https://user-images.githubusercontent.com/6320070/127807824-1eebd977-1e8c-451e-b66c-ad6c5e89b3e9.png)

**Comment by mydockfinder** [comment]
emmmm&nbsp; 原来istat已经变了啊，我使用的旧版显示的MEN，下次更新改一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月2日(星期一) 中午1:22
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] request: change &quot;MEN&quot; to &quot;MEM&quot; in English translation (#174)





 
Thank you for the reply!
 
I believe iStat says "MEM" and not "MEN":

**Comment by twonth** [comment]
Thank you!

**Comment by twonth** [comment]
I see this is fixed already. Thank you again!
