### ISSUE TITLE
内存占用500+M，内存泄漏？

### ISSUE THREAD

**Issue by db-one** [mydockfinder/mydockfinder#181]
![image](https://user-images.githubusercontent.com/20243226/128862615-1ab407d9-4347-4080-b1e2-c5d9b967b2ea.png)
内存占用500多M了，内存泄漏？平时没太注意，今天突然发现的

**Comment by mydockfinder** [comment]
看看过一会他可能自己降回去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上7:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 内存占用500+M，内存泄漏？ (#181)





 

 内存占用500多M了，内存泄漏？平时没太注意，今天突然发现的
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/128871240-6866fb87-e201-44a9-9b70-25cf971039e0.png)
现在还是五百多

**Comment by mydockfinder** [comment]
那就重启dock吧。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 晚上9:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 内存占用500+M，内存泄漏？ (#181)





 

 现在还是五百多
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by db-one** [comment]
嗯 好的

**Comment by db-one** [comment]
![动画](https://user-images.githubusercontent.com/20243226/128950905-c42fdc33-c583-48f6-8d72-d5179623feae.gif)
![image](https://user-images.githubusercontent.com/20243226/128950953-b70eb60c-8faa-4626-af29-2f1e1eca9174.png)
最近还遇到一个比较神奇的事情，阿里旺旺打开变成我的文档文件夹了
配置文件里面都是正常的，但打开就是没有启动程序，而是打开了文件夹，尝试删除图标，重新添加还是一样，不知道什么情况，dock版本是最新的，启动台里面是正常的

**Comment by mydockfinder** [comment]
嗯 我知道这个bug，是因为阿里旺旺的路径里面有个下划线的事 _




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 上午8:19
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 内存占用500+M，内存泄漏？ (#181)





 

 
 最近还遇到一个比较神奇的事情，阿里旺旺打开变成我的文档文件夹了
 配置文件里面都是正常的，但打开就是没有启动程序，而是打开了文件夹，尝试删除图标，重新添加还是一样，不知道什么情况，dock版本是最新的，启动台里面是正常的
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by db-one** [comment]
嗯 好的
