### ISSUE TITLE
软件太好用了 但我也遇到一点小问题 关于在processon全屏截图时候遇到的

### ISSUE THREAD

**Issue by atumu** [mydockfinder/mydockfinder#182]
首先介绍一下环境:
win10、**FastStone Capture**(截屏软件，可以**捕捉滚动窗口**)、**Processon**（web版的思维导图）

我要做的事就是：
在processon里捕捉滚动窗口来截图（没办法，Processon里太多收费克隆）

问题复现过程： 
本来在Chrome里F11全屏模式下，Mydock会被隐藏不再显示（**作者的这个功能很用心，点赞！**），但在Processon里的思维导图全屏页面下， **使用FastStone Capture去捕捉滚动窗口， Mydock却一直跳出来，没法隐藏**，只能忍心关掉Mydock软件再去截图。

不知道这个算不算问题，估计您不容易复现，特此附上软件地址：
[FastStone Capture](https://www.ghxi.com/faststone.html)
[Processon](https://www.processon.com/)

**Comment by mydockfinder** [comment]
我能说edge自带全网页的截图吗。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 晚上8:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 软件太好用了 但我也遇到一点小问题 关于在processon全屏截图时候遇到的 (#182)





 
首先介绍一下环境:
 win10、FastStone Capture(截屏软件，可以捕捉滚动窗口)、Processon（web版的思维导图）
 
我要做的事就是：
 在processon里捕捉滚动窗口来截图（没办法，Processon里太多收费克隆）
 
问题复现过程：
 本来在Chrome里F11全屏模式下，Mydock会被隐藏不再显示（作者的这个功能很用心，点赞！），但在Processon里的思维导图全屏页面下， 使用FastStone Capture去捕捉滚动窗口， Mydock却一直跳出来，没法隐藏，只能忍心关掉Mydock软件再去截图。
 
不知道这个算不算问题，估计您不容易复现，特此附上软件地址：
 FastStone Capture
 Processon
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by atumu** [comment]
嘿，作者非常有开发经验嘛，遇到问题先尝试解决提出问题的人 😄 

可惜edge的网页捕获功能在Processon全屏模式（需要点那个按钮，不是F11哦）下无效。

**Comment by mydockfinder** [comment]
emmmm&nbsp; 好吧 对了那个截图软件是不是所有网页F11全屏情况下截图dock都会出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 晚上10:03
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 软件太好用了 但我也遇到一点小问题 关于在processon全屏截图时候遇到的 (#182)





 
嘿，作者非常有开发经验嘛，遇到问题先尝试解决提出问题的人 😄
 
可惜edge的网页捕获功能在Processon全屏模式（需要点那个按钮，不是F11哦）下无效。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by atumu** [comment]
确实是呢， 重新验证了下。 无论是否在网页全屏（不分浏览器），还是在文件夹，或者Word之类的 ， 只要是用那个软件**捕捉滚动窗口**， dock就会出现。

**Comment by mydockfinder** [comment]
好的 我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月11日(星期三) 晚上7:56
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 软件太好用了 但我也遇到一点小问题 关于在processon全屏截图时候遇到的 (#182)





 
确实是呢， 重新验证了下。 无论是否在网页全屏（不分浏览器），还是在文件夹，或者Word之类的 ， 只要是用那个软件捕捉滚动窗口， dock就会出现。
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mydockfinder** [comment]
对了 我想到一个永久的办法，打开截图的时候dock上面有没有那个截图软件的图标，如果有的话右键设置独立显示隐藏模式，选永远隐藏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 晚上7:56
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 软件太好用了 但我也遇到一点小问题 关于在processon全屏截图时候遇到的 (#182)





 
确实是呢， 重新验证了下。 无论是否在网页全屏（不分浏览器），还是在文件夹，或者Word之类的 ， 只要是用那个软件捕捉滚动窗口， dock就会出现。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
