### ISSUE TITLE
English Translation is a mess.

### ISSUE THREAD

**Issue by xaryangupta** [mydockfinder/mydockfinder#206]
Please assign English translation work to someone else. The current English translation is absolutely horrendous and improper. Thanks for the amazing app though. :)

**Comment by mydockfinder** [comment]
我是自己一个人开发的，没有其他人帮我，都是用的谷歌翻译。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 凌晨3:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] English Translation is a mess. (#206)





 
Please assign English translation work to someone else. The current English translation is absolutely horrendous and improper. Thanks for the amazing app though. :)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Movisivi** [comment]
Suggest examples of " horrendous and improper." aside from the obvious Dormant instead of Hibernate

**Comment by xaryangupta** [comment]
Don't even get me started. The entire settings menu is hard to navigate. Many things aren't even translated properly and is in Chinese. But then dev should have handed the English translation to someone.

**Comment by mydockfinder** [comment]
好像翻译是挺可怕的，我一句也没看懂你说的什么。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 下午2:44
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] English Translation is a mess. (#206)





 
Don't even get me started. The entire settings menu is hard to navigate. Many things aren't even translated properly and is in Chinese. But then dev should have handed the English translation to someone.
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Movisivi** [comment]
> 
> 
> Don't even get me started. The entire settings menu is hard to navigate. Many things aren't even translated properly and is in Chinese. 

Screenshots? I'm in the settings daily and when I select English I only see English

**Comment by VladCarlsson** [comment]
Don't like it, don't use it! He's developing this on his own and he has done a fine job. The app will improve and the translations as well.

**Comment by xaryangupta** [comment]
There comes the ever-toxic reply from someone. 

> If you don't like it, don't use it! He's developing this on his own and he has done a fine job. The app will improve and the translations as well.

Good job with whataboutery!

**Comment by VladCarlsson** [comment]
The only toxic person here is you!
