### ISSUE TITLE
win11无法正常运行

### ISSUE THREAD

**Issue by ljynfo** [mydockfinder/mydockfinder#211]
按照教程安装了VS环境，打卡了图形选项，运行程序，任务管理里面有 Dock_64.exe正在运行，但是没有界面，请问怎么办？

**Comment by mydockfinder** [comment]
win11版本号




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 中午12:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
按照教程安装了VS环境，打卡了图形选项，运行程序，任务管理里面有 Dock_64.exe正在运行，但是没有界面，请问怎么办？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
![image](https://user-images.githubusercontent.com/42232422/132935856-f197c0e3-4c1e-4aa7-8ecd-7814453b1fb1.png)

**Comment by mydockfinder** [comment]
系统设置&nbsp; - 系统 -关于




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:12
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 

 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2021.‎9.‎3
操作系统版本	22000.184
序列号	PF2AL134
体验	Windows 功能体验包 1000.22000.184.0

**Comment by mydockfinder** [comment]
第一次用吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:14
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
版本	Windows 11 家庭中文版
 版本	21H2
 安装日期	‎2021.‎9.‎3
 操作系统版本	22000.184
 序列号	PF2AL134
 体验	Windows 功能体验包 1000.22000.184.0
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
之前win10电脑用过一次，但时间不久，后来换了mac，现在又换电脑了，主力机是现在这台

**Comment by mydockfinder** [comment]
配置文件都是之前的那个吗，还是重新安装的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:17
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
之前win10电脑用过一次，但时间不久，后来换了mac，现在又换电脑了，主力机是现在这台
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
重新下载的，官网的exe解压、蓝组云的压缩包都试过了，任务管理器正在运行，就是没界面上么有反应

**Comment by mydockfinder** [comment]
打开dock目录config.ini文件，搜索mydockfinder&nbsp; 然后myfinder=1改成0试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:23
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
重新下载的，官网的exe解压、蓝组云的压缩包都试过了，任务管理器正在运行，就是没界面上么有反应
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
我下载链接是https://mydockfinder.lanzoux.com/b03mlebmj
没有在dock目录找到config.ini文件

**Comment by mydockfinder** [comment]
链接没有问题，你点的是mydock.exe还是dock.exe还是dock_64.exe



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:29
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
我下载链接是https://mydockfinder.lanzoux.com/b03mlebmj
 没有在dock目录找到config.ini文件
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
三个我都点过，在任务管理器都会出现Dock_64.exe正在运行，但是没有界面

**Comment by mydockfinder** [comment]
文件版本是最新的5.10.1吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:33
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
三个我都点过，在任务管理器都会出现Dock_64.exe正在运行，但是没有界面
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
![image](https://user-images.githubusercontent.com/42232422/132936351-7aac036b-13da-40c8-821f-5641383d767f.png)
是这个，不清楚版本，官网下载的exe解压的也试过

**Comment by mydockfinder** [comment]
那应该是最新的，具体怎么回事我还真的不清楚了，连配置文件都没有生成基本上都没启动起来，或者试一下管理员模式运行，还有软件别放在C盘




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:36
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 

 是这个，不清楚版本，官网下载的exe解压的也试过
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ljynfo** [comment]
以管理员方式运行还是一样的（界面没反应），可不可以请求帮忙远程调试一下解决一下呢

**Comment by mydockfinder** [comment]
121817313 QQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 中午12:54
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] win11无法正常运行 (#211)





 
以管理员方式运行还是一样的（界面没反应），可不可以请求帮忙远程调试一下解决一下呢
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
