### ISSUE TITLE
关于访达预览的问题

### ISSUE THREAD

**Issue by HaoShen2021** [mydockfinder/mydockfinder#212]
访达打开一个窗口且没有最小化时，如图
![360截图20210912155545917](https://user-images.githubusercontent.com/90556839/132986384-67734063-2de3-4456-9dbc-07db170d0091.jpg)
PS：开启{最小化到图标}

**Comment by HaoShen2021** [comment]
打错了 窗口最小化到dock

**Comment by mydockfinder** [comment]
这个版本的bug，先别勾选最小化到图标




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月12日(星期天) 晚上7:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 关于访达预览的问题 (#212)





 
打错了 窗口最小化到dock
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
好的 谢谢 期待修复😀
