### ISSUE TITLE
关于最小化至应用图标的问题

### ISSUE THREAD

**Issue by Pinghigh** [mydockfinder/mydockfinder#213]
不完善，例如edge最小化时不会最小化到图标上

**Comment by HaoShen2021** [comment]
我的Chrome也是

**Comment by HaoShen2021** [comment]
还有一个程序自定义名称后最小化至应用图标后，再次最大化，滑动dock就这个程序的图标不显示标签，顶部finder的标签又会恢复改之前的标题

**Comment by HaoShen2021** [comment]
还有一个程序自定义名称后最小化至应用图标后，再次最大化，滑动dock就这个程序的图标不显示标签，顶部finder的标题又会恢复改之前的标题

**Comment by Movisivi** [comment]
@Pinghigh @HaoShen2021 

Works here, make sure to enable "minimize windows into application icon" in mydock minimize window settings

**Comment by mydockfinder** [comment]
这个版本的最小化到图标有点问题，先别勾选，容易丢失图标和标签变空白




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月12日(星期天) 晚上9:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 关于最小化至应用图标的问题 (#213)





 
@Pinghigh @HaoShen2021
 
Works here, make sure to enable "minimize windows into application icon" in mydock minimize window settings
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pinghigh** [comment]
> 这个版本的最小化到图标有点问题，先别勾选，容易丢失图标和标签变空白
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年9月12日(星期天) 晚上9:59 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 关于最小化至应用图标的问题 (#213) @Pinghigh @HaoShen2021 Works here, make sure to enable "minimize windows into application icon" in mydock minimize window settings &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

感谢回复
