### ISSUE TITLE
天气不能正常显示

### ISSUE THREAD

**Issue by PIERCEEE34** [mydockfinder/mydockfinder#216]
我在config末尾添加了城市代码，但是并不能正常显示当前天气，只有一个默认的天气图标，请问该如何解决

**Comment by mydockfinder** [comment]
新版的天气不是城市代码了，是城市的经纬度




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午3:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 天气不能正常显示 (#216)





 
我在config末尾添加了城市代码，但是并不能正常显示当前天气，只有一个默认的天气图标，请问该如何解决
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PIERCEEE34** [comment]
> 新版的天气不是城市代码了，是城市的经纬度
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" ***@***.***&gt;; 发送时间:&nbsp;2021年9月14日(星期二) 下午3:41 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 天气不能正常显示 (#216) 我在config末尾添加了城市代码，但是并不能正常显示当前天气，只有一个默认的天气图标，请问该如何解决 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我再重新打开发现已经自动变为经纬度了，但是还是不能显示，不知道是什么原因
