### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by HaoShen2021** [mydockfinder/mydockfinder#217]
作者你好！希望在改写界面库时也添加一下这个功能，谢谢🙏
![2FD959B2-8AD5-48D4-82F3-7FE942AD994A](https://user-images.githubusercontent.com/90556839/133458126-7a067191-eae0-4924-a462-6007c047c945.jpeg)

**Comment by mydockfinder** [comment]
emmm&nbsp; 这个不会做。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 晚上10:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
作者你好！希望在改写界面库时也添加一下这个功能，谢谢🙏
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
我发现 使用麦克风时托盘里有个图标
![40A0DDA5-5C57-4F88-A7D2-3FB9F1DE1D3A](https://user-images.githubusercontent.com/90556839/133611840-d798161a-674c-44a6-b940-4f772e9d06f7.jpeg)
是不是可以让程序读取此内容以完成本功能？

**Comment by mydockfinder** [comment]
这倒是个思路，我回来试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
我发现 使用麦克风时托盘里有个图标
 
 是不是可以让程序读取此内容以完成本功能？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
好的

**Comment by HaoShen2021** [comment]
再提个小建议，重写界面库后把样式变成这样
![6236C9F5-D1C4-410D-8B6E-6EAE6C88745F](https://user-images.githubusercontent.com/90556839/133615590-fddcbb56-963f-4b4b-b121-75adabd0e9d0.png)
（真）谢谢🙏

**Comment by mydockfinder** [comment]
我也是这么打算的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
再提个小建议，重写界面库后把样式变成这样
 
 （真）谢谢🙏
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
太好了，期待期待！

**Comment by HaoShen2021** [comment]
预计什么时候发布？

**Comment by mydockfinder** [comment]
怎么也要十月一，这几天移植改网站了，软件一直没写




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上8:56
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
预计什么时候发布？
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
😄

**Comment by HaoShen2021** [comment]
这个主题很好看😆

**Comment by mydockfinder** [comment]
不是主题，全都是我自己做的，主题用WP自带的2021就为了那个切换暗色模式




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上9:05
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
这个主题很好看😆
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
别告诉我标题栏的模糊是winui哈哈

**Comment by mydockfinder** [comment]
不是，苹果官网的代码，YouTube有教程




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上9:08
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
别告诉我标题栏的模糊是winui哈哈
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
😄

**Comment by HaoShen2021** [comment]
再提一个建议 可不可以自定义最小化到dock的动画速度？

**Comment by mydockfinder** [comment]
你是嫌有时快有时慢吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上9:17
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
再提一个建议 可不可以自定义最小化到dock的动画速度？
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
是的

**Comment by mydockfinder** [comment]
没事 下个版本就好了，我加上了垂直同步，之前的版本都是手动加的延迟控制帧数，如果其他exe调整了系统cpu计时器就会变成忽快忽慢，但是开了垂直同步就没有这个问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上9:21
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
是的
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
好的

**Comment by HaoShen2021** [comment]
还有，能不能让壁纸深浅色跟随系统而不跟随日出日落？

**Comment by HaoShen2021** [comment]
另外，修复移除图标时标签一边是新版，一边是旧版

https://user-images.githubusercontent.com/90556839/133622823-30131c8c-48b9-4599-a86b-d2c958a45851.MP4

**Comment by mydockfinder** [comment]
我没看懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 功能建议 (#217)





 
另外，修复移除图标时标签一边是新版，一边是旧版
 
https://user-images.githubusercontent.com/90556839/133622823-30131c8c-48b9-4599-a86b-d2c958a45851.MP4
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HaoShen2021** [comment]
![image](https://user-images.githubusercontent.com/90556839/133628670-ea0837ce-65d4-4f4e-b10f-f6a3f380857d.png)
左右不对称
