### ISSUE TITLE
一些小 bug

### ISSUE THREAD

**Issue by HaoShen2021** [mydockfinder/mydockfinder#222]
1-“移除”标签左右不对称，一边是新标签，一边是旧标签
![50D16730-280C-47A1-B689-5E6A9AD9EABB](https://user-images.githubusercontent.com/90556839/133781064-0ccfa3ed-3710-466e-82c4-fdd366a80827.png)

**Comment by HaoShen2021** [comment]
2，笔记本复制投屏到电视，电视上的finder模糊正常，而字和图标显示比例不正常。

**Comment by HaoShen2021** [comment]
3，投屏到电视时，点开dock里的文件夹，展开时，dock的win UI模糊闪烁

**Comment by HaoShen2021** [comment]
4，壁纸是否能像macOS一样，深浅色跟随系统深浅色？

**Comment by mydockfinder** [comment]
1、那还是不居中没有所谓的一边新一边旧
2、3、这个不是很清楚，要是模糊先说只能说是系统问题，WinUI模糊和finder图标都是系统渲染的
4、回来想想




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月17日(星期五) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 一些小 bug (#222)





 
4，壁纸是否能像macOS一样，深浅色跟随系统深浅色？
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
