### ISSUE TITLE
touchscreen issue: item label in Dock doesn't close

### ISSUE THREAD

**Issue by twonth** [mydockfinder/mydockfinder#223]
![2021-09-18](https://user-images.githubusercontent.com/6320070/133899647-33c3d018-f676-49ad-bc5a-c9159ca029d9.jpg)

I use mydockfinder on a touchscreen tablet. I have disabled "Icon zoomed size".

Usually it works great. Except:

The item label on the dock sometimes does not disappear when it should. (For example, "Microsoft Edge" in the above photo.)  I would expect the program label to disappear as soon as I click somewhere else. But this doesn't always work. Sometimes the label disappears temporarily, but then it reappears.

This issue also prevents hiding the dock sometmies. mydockfinder seems to think the label should be displayed. In these situations, pressing the hide dock hotkey does not work.

I do not have this issue on my laptop. It only happens on my touchscreen devices.

**A simple fix might be to add an option to disable these labels**  ?

**Comment by mydockfinder** [comment]
下个版本会加一个不显示标签的功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月19日(星期天) 凌晨2:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] touchscreen issue: item label in Dock doesn't close (#223)





 

 
I use mydockfinder on a touchscreen tablet. I have disabled "Icon zoomed size".
 
Usually it works great. Except:
 
The item label on the dock sometimes does not disappear when it should. (For example, "Microsoft Edge" in the above photo.)  I would expect the program label to disappear as soon as I interact with the program. But this doesn't always work on my touchscreen. Sometimes the label disappears temporarily, but then it reappears as soon as I stop touching the screen.
 
This issue also prevents hiding the dock reliably. mydockfinder seems to think the label should be displayed. In these situations, pressing the hide dock key does not work.
 
I do not have this issue on my laptop. It only happens on my touchscreen devices.
 
A simple fix might be to add an option to disable these labels  ?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by twonth** [comment]
Thank you!

**Comment by twonth** [comment]
Thank you for the hide labels feature!

Unfortunately, I still sometimes have the issue where programs refuse to hide when the hotkey is pressed. The dock starts to hide. But it comes back up before it has fully hid. There is a kind of "stutter".  I thought this was related to the program labels but it seems to be a different issue.

I will mark this issue as closed and maybe open a new one.
