### ISSUE TITLE
no updates?!?!

### ISSUE THREAD

**Issue by teddtastic** [mydockfinder/mydockfinder#251]
hey have you discontinued the project or you're working on something great?

**Comment by mydockfinder** [comment]
准备上架steam平台




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 中午1:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] no updates?!?! (Issue #251)





 
hey have you discontinued the project or you're working on something great?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by teddtastic** [comment]
i didn't understand

**Comment by mydockfinder** [comment]
valve steam




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 中午1:08
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] no updates?!?! (Issue #251)





 
i didn't understand
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by teddtastic** [comment]
what does that have to do with updates
like I'm not much of a coder or anything so please explain

**Comment by mydockfinder** [comment]
是要借助steam平台的创意工坊，来增加切换皮肤和更换图标功能




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月29日(星期五) 中午1:16
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] no updates?!?! (Issue #251)





 
what does that have to do with updates
 like I'm not much of a coder or anything so please explain
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by VladCarlsson** [comment]
@teddtastic what he means he is working on getting the app released on Steam with support for workshop which will increase it's functionality, it will make it easier to get icons and even new skins for it.

I'm really excited for the Steam release!

**Comment by teddtastic** [comment]
aaah okay
thanks
i don't use steam but I can understand your excitement
Cheers!

**Comment by VladCarlsson** [comment]
> aaah okay thanks i don't use steam but I can understand your excitement Cheers!

Oh :( Well maybe he's going to have a non-steam version with less features on the official website, who knows...
I'm excited because workshop could open lots of possibilities for faster and easier customization.
Have a lovely day 😊

**Comment by alfaaarex** [comment]
Excited af

**Comment by teddtastic** [comment]
> > aaah okay thanks i don't use steam but I can understand your excitement Cheers!
> 
> Oh :( Well maybe he's going to have a non-steam version with less features on the official website, who knows... I'm excited because workshop could open lots of possibilities for faster and easier customization. Have a lovely day 😊
