### ISSUE TITLE
What is the actual license of this project & a few questions?

### ISSUE THREAD

**Issue by rbreaves** [mydockfinder/mydockfinder#256]
I have a few basic questions

1. ) Do you plan to commercialize this app?
2. ) Do you or have you already released the source code to this app? If so what will the license be?
3. ) Are there any ads, telemetry or tracking software of any kind in your software?

**Comment by mydockfinder** [comment]
1、是的，准备上架steam平台，现在的算是一个免费试用版
2、没有开源
3、没有任何的广告、监控等，唯一的只有一个定位，是天气预报用的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 上午8:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] What is the actual license of this project &amp; a few questions? (Issue #256)





 
I have a few basic questions
  
) Do you plan to commercialize this app?
 
) Do you or have you already released the source code to this app? If so what will the license be?
 
) Are there any ads, telemetry or tracking software of any kind in your software?
  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rbreaves** [comment]
Thank you! You responded really quickly too!
