### ISSUE TITLE
Display Scaling

### ISSUE THREAD

**Issue by alishtamimi** [mydockfinder/mydockfinder#258]
I found that the dock can't recognize the current display calling, it relies on the user to manually scale the icon size and the overall menu scaling. The problem with my setup, that I use two different monitors separately, one on 150% display scaling and the other is 100% display scaling. so whenever I change my monitor I have to manually change the scaling settings.

**Comment by alishtamimi** [comment]
You can Change each monitor scaling separately. So the app has different monitor files.

**Comment by mydockfinder** [comment]
这个不是很好弄，因为切换全局缩小要全部渲染一次的，如果来回频繁的切换容易崩溃，，，，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月6日(星期六) 凌晨0:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Display Scaling (Issue #258)





 
I found that the dock can't recognize the current display calling, it relies on the user to manually scale the icon size and the overall menu scaling. The problem with my setup, that I use two different monitors separately, one on 150% display scaling and the other is 100% display scaling. so whenever I change my monitor I have to manually change the scaling settings.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
