### ISSUE TITLE
Simple Question and 700th Star

### ISSUE THREAD

**Issue by turannul** [mydockfinder/mydockfinder#261]
I can disable dock which means Menu bar only,i would appreciate it if it could be done
Translated wth Google：我可以禁用dock，这意味着只有菜单栏，如果可以做到，我将不胜感激

**Comment by mydockfinder** [comment]
目前还不可以，因为大部分的功能检测都在dock里面了，那些代码还没有剥离出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月7日(星期天) 中午12:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Simple Question and 700th Star (Issue #261)





 
I can disable dock which means Menu bar only,i would appreciate it if it could be done
 Translated wth Google：我可以禁用dock，这意味着只有菜单栏，如果可以做到，我将不胜感激
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rbreaves** [comment]
What I’ve done is set the dock to the sides & as small as it can go & let it hide for now. Although the dock isn’t bad once additional options are added.

The lack of dual monitor support is problematic, but I’ve been using sandboxie to help run it twice over. It then wants to launch apps or do things in the sandbox though :/.

**Comment by mydockfinder** [comment]
真的是不建议运行两次，对GPU的负担很大，主要是模糊太费GPU了。过着后面我可以出每个显示器都显示dock，但是只能激活的屏幕dock背景是模糊的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月8日(星期一) 凌晨3:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Simple Question and 700th Star (Issue #261)





 
What I’ve done is set the dock to the sides &amp; as small as it can go &amp; let it hide for now. Although the dock isn’t bad once additional options are added.
 
The lack of dual monitor support is problematic, but I’ve been using sandboxie to help run it twice over. It then wants to launch apps or do things in the sandbox though :/.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
