### ISSUE TITLE
微信浏览器和dock不适配

### ISSUE THREAD

**Issue by yxzlwz** [mydockfinder/mydockfinder#269]
全屏模式dock无法唤醒或无法隐藏

**Comment by mydockfinder** [comment]
是从微信打开新闻吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 微信浏览器和dock不适配 (Issue #269)





 
全屏模式dock无法唤醒或无法隐藏
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
嗯嗯就是任何公众号的文章界面等电脑微信打开的链接

**Comment by mydockfinder** [comment]
我测试了没事啊，你是不是关闭了myfinder而且隐藏了系统任务栏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 上午10:26
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信浏览器和dock不适配 (Issue #269)





 
嗯嗯就是任何公众号的文章界面等电脑微信打开的链接
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
finder是开启的自动隐藏显示，任务栏隐藏了

全屏后finder和dock都无法唤醒

**Comment by mydockfinder** [comment]
那就对了，myfinder和系统任务栏要显示一个，因为一个都不显示的话有的窗口最大化会激活系统的全屏机制，激活全屏后dock是不能手动激活的

**Comment by yxzlwz** [comment]
好的明白了，那我还是开启finder吧

感谢大佬
