### ISSUE TITLE
亮度调节bug

### ISSUE THREAD

**Issue by yxzlwz** [mydockfinder/mydockfinder#270]
我使用键盘快捷键进行亮度调节时出现如下问题：

- 我摁下两次亮度调高两次亮度调低，实际的亮度变化没有问题，但是程序的弹窗错了（我使用mac样式）
- 程序的反馈是亮度升高了三次降低了一次
- 反之我摁下两次减小两次增大，他也会减小三次增大一次
- 按一次增大两次减小，亮度条的反馈是增大两次减小一次
- 若我在最低亮度时按一次增大一次减小，则提示框被唤醒后第一次按增大时提示条不变，第二次按减小时提示条增大一个
- 简单说就是第一次唤醒这个提示框的时候的按键多检测了一次

**Comment by mydockfinder** [comment]
是用的fn快捷键调节的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270)





 
我使用键盘快捷键进行亮度调节时出现如下问题：
  
我摁下两次亮度调高两次亮度调低，实际的亮度变化没有问题，但是程序的弹窗错了（我使用mac样式）
 
程序的反馈是亮度升高了三次降低了一次
 
反之我摁下两次减小两次增大，他也会减小三次增大一次
 
按一次增大两次减小，亮度条的反馈是增大两次减小一次
 
若我在最低亮度时按一次增大一次减小，则提示框被唤醒后第一次按增大时提示条不变，第二次按减小时提示条增大一个
 
简单说就是第一次唤醒这个提示框的时候的按键多检测了一次
  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
> 是用的fn快捷键调节的吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月14日(星期天) 上午10:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270) 我使用键盘快捷键进行亮度调节时出现如下问题： 我摁下两次亮度调高两次亮度调低，实际的亮度变化没有问题，但是程序的弹窗错了（我使用mac样式） 程序的反馈是亮度升高了三次降低了一次 反之我摁下两次减小两次增大，他也会减小三次增大一次 按一次增大两次减小，亮度条的反馈是增大两次减小一次 若我在最低亮度时按一次增大一次减小，则提示框被唤醒后第一次按增大时提示条不变，第二次按减小时提示条增大一个 简单说就是第一次唤醒这个提示框的时候的按键多检测了一次 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

是的

**Comment by mydockfinder** [comment]
好吧，我尽量。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 上午10:39
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270)





  
是用的fn快捷键调节的吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年11月14日(星期天) 上午10:36 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270) 我使用键盘快捷键进行亮度调节时出现如下问题： 我摁下两次亮度调高两次亮度调低，实际的亮度变化没有问题，但是程序的弹窗错了（我使用mac样式） 程序的反馈是亮度升高了三次降低了一次 反之我摁下两次减小两次增大，他也会减小三次增大一次 按一次增大两次减小，亮度条的反馈是增大两次减小一次 若我在最低亮度时按一次增大一次减小，则提示框被唤醒后第一次按增大时提示条不变，第二次按减小时提示条增大一个 简单说就是第一次唤醒这个提示框的时候的按键多检测了一次 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
是的
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
大佬加油！牛的！

另，恭喜开发者mydockfinder成为半商业项目！不使用steam，就等uwp了

**Comment by mydockfinder** [comment]
不是UWP，微软商店可以上传exe了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 上午10:41
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270)





 
大佬加油！牛的！
 
另，恭喜开发者mydockfinder成为半商业项目！不使用steam，就等uwp了
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
哈哈哈哈哈好的，反正坐等ms store下载喽

**Comment by mydockfinder** [comment]
最早也得明年过完春节了，我先忙steam创意工坊



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 上午10:44
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270)





 
哈哈哈哈哈好的，反正坐等ms store下载喽
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
嗯嗯

**Comment by yxzlwz** [comment]
> 好吧，我尽量。。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月14日(星期天) 上午10:39 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270) 是用的fn快捷键调节的吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年11月14日(星期天) 上午10:36 收件人: @.&gt;; 抄送: @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270) 我使用键盘快捷键进行亮度调节时出现如下问题： 我摁下两次亮度调高两次亮度调低，实际的亮度变化没有问题，但是程序的弹窗错了（我使用mac样式） 程序的反馈是亮度升高了三次降低了一次 反之我摁下两次减小两次增大，他也会减小三次增大一次 按一次增大两次减小，亮度条的反馈是增大两次减小一次 若我在最低亮度时按一次增大一次减小，则提示框被唤醒后第一次按增大时提示条不变，第二次按减小时提示条增大一个 简单说就是第一次唤醒这个提示框的时候的按键多检测了一次 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 是的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好耶，v1.6.6版本修复这个问题了！居然都不写在更新日志里，差点没发现

**Comment by mydockfinder** [comment]
修了吗。。。。。。 我主要自己没事也测试不出来，不过我是打算下个版本修的。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 中午12:07
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270)





 
Closed #270.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
> 修了吗。。。。。。 我主要自己没事也测试不出来，不过我是打算下个版本修的。。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年2月15日(星期二) 中午12:07 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 亮度调节bug (Issue #270) Closed #270. &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

我这边是好的，反正下个版本别弄坏了就行哈哈哈哈哈哈哈
