### ISSUE TITLE
从微软商店安装的程序应该怎么加到 dock 当中呢？

### ISSUE THREAD

**Issue by tristone13th** [mydockfinder/mydockfinder#273]
请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？

**Comment by mydockfinder** [comment]
两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock
第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 中午12:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273)





 
请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tristone13th** [comment]
> 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" ***@***.***&gt;; 发送时间:&nbsp;2021年11月15日(星期一) 中午12:21 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

非常感谢，steam 上线后一定第一时间购买支持！另外再问一句，用您的这种方式操作后图标会有点奇怪，会变小同时背景会变成蓝色，这种情况你知道怎么解决吗？

**Comment by tristone13th** [comment]
> 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" ***@***.***&gt;; 发送时间:&nbsp;2021年11月15日(星期一) 中午12:21 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

已经通过重新设置图标解决，谢谢!

**Comment by mydockfinder** [comment]
谢谢，steam版本也会优化UWP图标的显示不会那么小了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 下午2:03
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273)





  
两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除
 …
 ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间: 2021年11月15日(星期一) 中午12:21 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
已经通过重新设置图标解决，谢谢!
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tristone13th** [comment]
> 谢谢，steam版本也会优化UWP图标的显示不会那么小了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月15日(星期一) 下午2:03 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除 … ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间: 2021年11月15日(星期一) 中午12:21 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 已经通过重新设置图标解决，谢谢! &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

谢谢哈，还有一个小问题，finder 栏点击后的菜单有一个选项是“开启窗口边界”，这是什么意思呀，好像开不开没区别。

**Comment by mydockfinder** [comment]
默认就是开的，如果有时候资源管理器崩溃重启了，myfinder窗口边界有可能会失效，那样就会挡住桌面图标或者最大化的窗口，那时候点一下窗口边界就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 中午11:15
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273)





  
谢谢，steam版本也会优化UWP图标的显示不会那么小了
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月15日(星期一) 下午2:03 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除 … ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间: 2021年11月15日(星期一) 中午12:21 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 已经通过重新设置图标解决，谢谢! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
谢谢哈，还有一个小问题，finder 栏点击后的菜单有一个选项是“开启窗口边界”，这是什么意思呀，好像开不开没区别。
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tristone13th** [comment]
> 默认就是开的，如果有时候资源管理器崩溃重启了，myfinder窗口边界有可能会失效，那样就会挡住桌面图标或者最大化的窗口，那时候点一下窗口边界就好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月16日(星期二) 中午11:15 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 谢谢，steam版本也会优化UWP图标的显示不会那么小了 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月15日(星期一) 下午2:03 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除 … ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间: 2021年11月15日(星期一) 中午12:21 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 已经通过重新设置图标解决，谢谢! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 谢谢哈，还有一个小问题，finder 栏点击后的菜单有一个选项是“开启窗口边界”，这是什么意思呀，好像开不开没区别。 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好的，感谢回答！不过还有两个小问题哈：
 - 从开启全屏的程序退出来后，原来存在的窗口可能会变大，导致 myfinder 栏可能会挡住窗口的最小化最大化关闭按钮；
 - myfinder 栏的图标点击不是很灵敏，比如搜索图标，有时候点击可以唤出，有时候点击没有响应。

**Comment by mydockfinder** [comment]
第一种情况你就可以点击开启窗口边界了，那样窗口就自己下来了，搜索是激活的系统搜索，其实就是后台安乐WIN+S，如果慢就是系统的事了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 中午11:24
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273)





  
默认就是开的，如果有时候资源管理器崩溃重启了，myfinder窗口边界有可能会失效，那样就会挡住桌面图标或者最大化的窗口，那时候点一下窗口边界就好了
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月16日(星期二) 中午11:15 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 谢谢，steam版本也会优化UWP图标的显示不会那么小了 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月15日(星期一) 下午2:03 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除 … ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间: 2021年11月15日(星期一) 中午12:21 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 已经通过重新设置图标解决，谢谢! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 谢谢哈，还有一个小问题，finder 栏点击后的菜单有一个选项是“开启窗口边界”，这是什么意思呀，好像开不开没区别。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
好的，感谢回答！不过还有两个小问题哈：
  
从开启全屏的程序退出来后，原来存在的窗口可能会变大，导致 myfinder 栏可能会挡住窗口的最小化最大化关闭按钮；
 
myfinder 栏的图标点击不是很灵敏，比如搜索图标，有时候点击可以唤出，有时候点击没有响应。
  
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tristone13th** [comment]
> 第一种情况你就可以点击开启窗口边界了，那样窗口就自己下来了，搜索是激活的系统搜索，其实就是后台安乐WIN+S，如果慢就是系统的事了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月16日(星期二) 中午11:24 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 默认就是开的，如果有时候资源管理器崩溃重启了，myfinder窗口边界有可能会失效，那样就会挡住桌面图标或者最大化的窗口，那时候点一下窗口边界就好了 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月16日(星期二) 中午11:15 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 谢谢，steam版本也会优化UWP图标的显示不会那么小了 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月15日(星期一) 下午2:03 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 两个办法，第一个直接打开你要添加的UWP程序，dock会显示出来他的图标右键保留在dock 第二个，开始菜单的快捷方式拽到桌面上面，他会生成一个新的快捷方式，然后桌面那个快捷方式拽进dock就可以了，然后那个桌面的快捷方式可以删除 … ------------------ 原始邮件 ------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间: 2021年11月15日(星期一) 中午12:21 @.&gt;; @.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 请问如果想要把一些在 Microsoft Store 当中下载的软件比如 ToDo 和 Windows Terminal 这些软件固定到 dock 上，应该怎么做呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 已经通过重新设置图标解决，谢谢! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 谢谢哈，还有一个小问题，finder 栏点击后的菜单有一个选项是“开启窗口边界”，这是什么意思呀，好像开不开没区别。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 好的，感谢回答！不过还有两个小问题哈： 从开启全屏的程序退出来后，原来存在的窗口可能会变大，导致 myfinder 栏可能会挡住窗口的最小化最大化关闭按钮； myfinder 栏的图标点击不是很灵敏，比如搜索图标，有时候点击可以唤出，有时候点击没有响应。 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好的，感谢回复，不过好像 finder 栏不只是搜索按钮有些不灵敏，有时候在打开三角的系统托盘栏后，在里面收录的程序上右键有时也会没有响应，这个您知道怎么回事吗？

**Comment by mydockfinder** [comment]
那是旧版的bug，steam版就好了

**Comment by tristone13th** [comment]
> 那是旧版的bug，steam版就好了

好的，感谢~

**Comment by tristone13th** [comment]
还有个问题，Microsoft store 里的应用怎么保存到启动台里呢？

**Comment by mydockfinder** [comment]
开始菜单里面拽到桌面或者其他地方，然后拽出来的快捷方式添加进去，然后拽出来的快捷方式可以删了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 晚上9:40
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273)





 
还有个问题，Microsoft store 里的应用怎么保存到启动台里呢？
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tristone13th** [comment]
> 开始菜单里面拽到桌面或者其他地方，然后拽出来的快捷方式添加进去，然后拽出来的快捷方式可以删了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月23日(星期二) 晚上9:40 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 还有个问题，Microsoft store 里的应用怎么保存到启动台里呢？ &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

谢谢~固定到开始屏幕的貌似不可以，需要打开应用列表之后才行，已经解决啦

**Comment by tristone13th** [comment]
> 开始菜单里面拽到桌面或者其他地方，然后拽出来的快捷方式添加进去，然后拽出来的快捷方式可以删了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月23日(星期二) 晚上9:40 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 还有个问题，Microsoft store 里的应用怎么保存到启动台里呢？ &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

还有就是左下角右下角监测貌似不是很灵敏，希望 steam 版能够解决这个问题~

**Comment by mydockfinder** [comment]
那个是防止误触 如果鼠标过去太快就会被忽略，要重新离开在到边角才能触发




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 晚上9:46
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273)





  
开始菜单里面拽到桌面或者其他地方，然后拽出来的快捷方式添加进去，然后拽出来的快捷方式可以删了
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年11月23日(星期二) 晚上9:40 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 从微软商店安装的程序应该怎么加到 dock 当中呢？ (Issue #273) 还有个问题，Microsoft store 里的应用怎么保存到启动台里呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
还有就是左下角右下角监测貌似不是很灵敏，希望 steam 版能够解决这个问题~
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tristone13th** [comment]
> 

玩明白了，谢谢！
