### ISSUE TITLE
steam版请问如何使用其他图标

### ISSUE THREAD

**Issue by codesensi** [mydockfinder/mydockfinder#287]
steam请问如何使用其他的图标包，自带的有点不太好看

**Comment by mydockfinder** [comment]
在themes文件夹里面了，直接替换图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月27日(星期六) 中午12:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] steam版请问如何使用其他图标 (Issue #287)





 
steam请问如何使用其他的图标包，自带的有点不太好看
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by codesensi** [comment]
> 



> 在themes文件夹里面了，直接替换图片
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月27日(星期六) 中午12:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] steam版请问如何使用其他图标 (Issue #287) steam请问如何使用其他的图标包，自带的有点不太好看 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
