### ISSUE TITLE
finder网络监控模块修改建议

### ISSUE THREAD

**Issue by yxzlwz** [mydockfinder/mydockfinder#289]
截图：https://pan.bilnn.cn/s/Jl3xCM

感觉网络留这么大空挺浪费的，能不能紧凑些

**Comment by mydockfinder** [comment]
等你看见1000.0KB的时候不嫌宽了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月28日(星期天) 上午10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] finder网络监控模块修改建议 (Issue #289)





 
截图：https://pan.bilnn.cn/s/Jl3xCM
 
感觉网络留这么大空挺浪费的，能不能紧凑些
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yxzlwz** [comment]
能不能删去左边两个箭头的图标

**Comment by yxzlwz** [comment]
?
