### ISSUE TITLE
Missing backup directory on steam version

### ISSUE THREAD

**Issue by joseehilton147** [mydockfinder/mydockfinder#290]
![image](https://user-images.githubusercontent.com/53986027/143787578-16ac1ec2-b6c6-4604-bbdc-acbeafdd48d2.png)

on steam version

![image](https://user-images.githubusercontent.com/53986027/143787596-be6ad31a-8ef8-49a8-ae88-f863f7b85f32.png)

**Comment by mydockfinder** [comment]
我忘记迁移这个数据了。。。
可以手动自己复制一下，旧版本浏览备份文件夹“open the backup folder”
复制到steam版本目录里面backup文件夹里面，如果没有对应的文件夹，手动新建一个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 凌晨5:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Missing backup directory on steam version (Issue #290)





 
github version
 

 
on steam version
 

 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
