### ISSUE TITLE
繁體中文語言錯誤

### ISSUE THREAD

**Issue by ghost** [mydockfinder/mydockfinder#291]
目前繁體中文翻譯有些有簡體中文的字或未完全翻譯好，目前我在 Pull requests 有提交修正後的繁體中文語言檔
https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/blob/release/language/Traditional%20Chinese.ini

修正某些句子符合繁體的說法
修正某些文字顯示為簡體的部分

![image](https://user-images.githubusercontent.com/24751265/143802613-da996545-b88c-4b8d-8ad0-649161054d2c.png)
![image](https://user-images.githubusercontent.com/24751265/143802601-88d3c10d-11c5-4874-a6e0-2aa02f82aa05.png)

**Comment by mydockfinder** [comment]
不好意思 我一忙就给忘了 回来加上




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 中午11:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (#291)





 
目前繁體中文翻譯有些有簡體中文的字或未完全翻譯好，目前我在 Pull requests 有提交修正後的繁體中文語言檔
 https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/blob/release/language/Traditional%20Chinese.ini
 
修正某些句子符合繁體的說法
 修正某些文字顯示為簡體的部分
 

 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mydockfinder** [comment]
请问除了任务栏还有其他翻译不准确的地方吗，因为我又新加了一些文字，不方便直接替换，就只改错误的地方




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 中午11:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (#291)





 
目前繁體中文翻譯有些有簡體中文的字或未完全翻譯好，目前我在 Pull requests 有提交修正後的繁體中文語言檔
 https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/blob/release/language/Traditional%20Chinese.ini
 
修正某些句子符合繁體的說法
 修正某些文字顯示為簡體的部分
 

 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
那這邊可以給新版本的語檔，我這邊可以再做修正一次可以嗎(?
修正完等等會丟上來(?

> 请问除了任务栏还有其他翻译不准确的地方吗，因为我又新加了一些文字，不方便直接替换，就只改错误的地方
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" ***@***.***&gt;; 发送时间:&nbsp;2021年11月29日(星期一) 中午11:12 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (#291) 目前繁體中文翻譯有些有簡體中文的字或未完全翻譯好，目前我在 Pull requests 有提交修正後的繁體中文語言檔 https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/blob/release/language/Traditional%20Chinese.ini 修正某些句子符合繁體的說法 修正某些文字顯示為簡體的部分 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mydockfinder** [comment]
我再仓库上传了新的繁体文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 中午11:47
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (Issue #291)





 
這邊可以給新版本的語檔，我這邊可以再做修正一次可以嗎(?
 修正完等等會丟上來(?
  
请问除了任务栏还有其他翻译不准确的地方吗，因为我又新加了一些文字，不方便直接替换，就只改错误的地方
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间:&nbsp;2021年11月29日(星期一) 中午11:12 @.&gt;; @.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (#291) 目前繁體中文翻譯有些有簡體中文的字或未完全翻譯好，目前我在 Pull requests 有提交修正後的繁體中文語言檔 https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/blob/release/language/Traditional%20Chinese.ini 修正某些句子符合繁體的說法 修正某些文字顯示為簡體的部分 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
這邊可以給新版簡體語系文件嗎(?
目前正在想確認新版的簡體和繁體區間部分，再做最後文句修正#/

> 我再仓库上传了新的繁体文件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" ***@***.***&gt;; 发送时间:&nbsp;2021年11月29日(星期一) 中午11:47 ***@***.***&gt;; 抄送:&nbsp;"№じ ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (Issue #291) 這邊可以給新版本的語檔，我這邊可以再做修正一次可以嗎(? 修正完等等會丟上來(? 请问除了任务栏还有其他翻译不准确的地方吗，因为我又新加了一些文字，不方便直接替换，就只改错误的地方 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mydockfinder/mydockfinder-for-Win10-Win11" @.&gt;; 发送时间:&nbsp;2021年11月29日(星期一) 中午11:12 @.&gt;; @.***&gt;; 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (#291) 目前繁體中文翻譯有些有簡體中文的字或未完全翻譯好，目前我在 Pull requests 有提交修正後的繁體中文語言檔 https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/blob/release/language/Traditional%20Chinese.ini 修正某些句子符合繁體的說法 修正某些文字顯示為簡體的部分 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mydockfinder** [comment]
仓库我已经上传了

**Comment by ghost** [comment]
Pull requests 以上傳更新好了/
https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/pull/280

**Comment by mydockfinder** [comment]
嗯 已经合并了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月29日(星期一) 中午1:05
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 繁體中文語言錯誤 (#291)





 
以上傳更新好了/
 #280
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
感謝作者/ (鞠躬
