### ISSUE TITLE
windows terminal固定到dock之后不能管理员模式运行

### ISSUE THREAD

**Issue by Pylogmon** [mydockfinder/mydockfinder#297]
![image](https://user-images.githubusercontent.com/59004461/144695484-118b4d39-0e4c-44b8-9746-1b5f2aabb13b.png)
直接打开没有问题，但是右键管理员模式运行就会报错。试过把dock用管理员模式运行也还是不行。

**Comment by mydockfinder** [comment]
终端是UWP程序，我不知道UWP怎么管理员模式启动。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 中午11:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] windows terminal固定到dock之后不能管理员模式运行 (Issue #297)





 

 直接打开没有问题，但是右键管理员模式运行就会报错。试过把dock用管理员模式运行也还是不行。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daleclack** [comment]
但是Windows11的Windows终端可以管理员启动，暂时还不清楚原理

**Comment by daleclack** [comment]
但是Windows11的Windows终端可以管理员启动，暂时还不清楚原理

**Comment by daleclack** [comment]
但是Windows11的Windows终端可以管理员启动，暂时还不清楚原理

**Comment by mydockfinder** [comment]
是的，我也不会。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月6日(星期一) 晚上11:31
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] windows terminal固定到dock之后不能管理员模式运行 (Issue #297)





 
但是Windows11的Windows终端可以管理员启动，暂时还不清楚原理
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
