### ISSUE TITLE
微信等应用收到消息后旁边会一直显示1

### ISSUE THREAD

**Issue by Pylogmon** [mydockfinder/mydockfinder#298]
![image](https://user-images.githubusercontent.com/59004461/144746634-4847ebba-b6fc-4183-a1e3-d36ba61182e8.png)
收到消息后旁边显示1，但是消息已读之后这个1会一直保持

**Comment by mydockfinder** [comment]
再切一下TIM窗口就没了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月5日(星期天) 晚上8:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298)





 

 收到消息后旁边显示1，但是消息已读之后这个1会一直保持
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
> 

不不不，一直在

**Comment by mydockfinder** [comment]
不可能啊，关了TIM窗口，然后点一下myfinder这个托盘图标




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月5日(星期天) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298)





   
不不不，一直在
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
> 不可能啊，关了TIM窗口，然后点一下myfinder这个托盘图标
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月5日(星期天) 晚上8:35 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298) 不不不，一直在 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我好像知道了，我的tim不在dock中保留，如果让他保留在dock就好了，但是不保留就有这个问题

**Comment by Pylogmon** [comment]
在dock的禁止列表里

**Comment by mydockfinder** [comment]
好吧，我也懂了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月5日(星期天) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298)





  
不可能啊，关了TIM窗口，然后点一下myfinder这个托盘图标
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月5日(星期天) 晚上8:35 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298) 不不不，一直在 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
我好像知道了，我的tim不在dock中保留，如果让他保留在dock就好了，但是不保留就有这个问题
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
算不算是bug

**Comment by mydockfinder** [comment]
算，但是你这禁止列表加的魔性。。。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月5日(星期天) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298)





 
在dock的禁止列表里
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
这样方便啊，符合习惯，在finder中就相当于是最小化列表了

**Comment by Pylogmon** [comment]
> 算，但是你这禁止列表加的魔性。。。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月5日(星期天) 晚上8:38 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298) 在dock的禁止列表里 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你永远不知道用户怎么玩，哈哈哈哈哈哈哈

**Comment by mydockfinder** [comment]
嗯。。。。。。
还没想过有这种操作




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月5日(星期天) 晚上8:43
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298)





  
算，但是你这禁止列表加的魔性。。。。。
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月5日(星期天) 晚上8:38 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 微信等应用收到消息后旁边会一直显示1 (Issue #298) 在dock的禁止列表里 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你永远不知道用户怎么玩，哈哈哈哈哈哈哈
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
