### ISSUE TITLE
能不能接管系统通知

### ISSUE THREAD

**Issue by Pylogmon** [mydockfinder/mydockfinder#299]
就右下角通知中心弹出来的那些通知

**Comment by mydockfinder** [comment]
只能显示，点击不能像系统一样激活对应的事件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午3:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 能不能接管系统通知 (Issue #299)





 
就右下角通知中心弹出来的那些通知
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
现在可以显示吗，怎么设置

**Comment by mydockfinder** [comment]
之前是可以显示的，但是都说不能激活我就砍了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 下午4:16
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 能不能接管系统通知 (Issue #299)





 
现在可以显示吗，怎么设置
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
