### ISSUE TITLE
在steam中打开之后，直接退出steam会卡住

### ISSUE THREAD

**Issue by Pylogmon** [mydockfinder/mydockfinder#302]
在steam中运行之后，如果直接退出steam的话，会显示正在关闭mydockfinder，而且一直关不掉，如果点击立即结束之后，steam关了，dock和任务栏都不显示，看任务管理器dock还在运行，而且cpu占用变得很高。

**Comment by mydockfinder** [comment]
直接在dock里面的steam图标右键 退出




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 下午5:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 在steam中打开之后，直接退出steam会卡住 (Issue #302)





 
在steam中运行之后，如果直接退出steam的话，会显示正在关闭mydockfinder，而且一直关不掉，如果点击立即结束之后，steam关了，dock和任务栏都不显示，看任务管理器dock还在运行，而且cpu占用变得很高。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pylogmon** [comment]
> 直接在dock里面的steam图标右键 退出
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年12月11日(星期六) 下午5:45
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 在steam中打开之后，直接退出steam会卡住 (Issue #302)
> 
> 
> 
> 
> 
>  
> 在steam中运行之后，如果直接退出steam的话，会显示正在关闭mydockfinder，而且一直关不掉，如果点击立即结束之后，steam关了，dock和任务栏都不显示，看任务管理器dock还在运行，而且cpu占用变得很高。
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

这种情况下是dock已经消失了，而且任务栏没出现，打开任务管理器发现还在运行

**Comment by mydockfinder** [comment]
我说的是dock里面的steam图标，直接右键强退




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月12日(星期天) 晚上8:26
***@***.***&gt;;
抄送:&nbsp;"№じ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mydockfinder/mydockfinder-for-Win10-Win11] 在steam中打开之后，直接退出steam会卡住 (Issue #302)





  
直接在dock里面的steam图标右键 退出
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    @.&gt;;
 发送时间:&nbsp;2021年12月11日(星期六) 下午5:45
 @.&gt;;
 @.***&gt;;
 主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] 在steam中打开之后，直接退出steam会卡住 (Issue #302)
 
在steam中运行之后，如果直接退出steam的话，会显示正在关闭mydockfinder，而且一直关不掉，如果点击立即结束之后，steam关了，dock和任务栏都不显示，看任务管理器dock还在运行，而且cpu占用变得很高。
 
—
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
  
这种情况下是dock已经消失了，而且任务栏没出现，打开任务管理器发现还在运行
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
