### ISSUE TITLE
MyDock -auto start at boot- not working!

### ISSUE THREAD

**Issue by onlytanmoy** [mydockfinder/mydockfinder#318]
Happy new year wishes.
Since last 2 days I can see MyDock is not automatically launching on my windows boot. I am using the Github version of the program. Previously there used to be an entry in my Taskmanager - Startup, I don't see that any more. Any help?

**Comment by mydockfinder** [comment]
新年快乐，新版的开机启动是使用的服务方式，可以看一下服务里面mydock是不是已经启动，如果不是启动的右键启动服务，下次开机就可以启动了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月1日(星期六) 晚上8:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] MyDock -auto start at boot- not working! (Issue #318)





 
Happy new year wishes.
 Since last 2 days I can see MyDock is not automatically launching on my windows boot. I am using the Github version of the program. Previously there used to be an entry in my Taskmanager - Startup, I don't see that any more. Any help?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by onlytanmoy** [comment]
Thanks for the swift response mate.
In one of my earlier tickets you mentioned about creative workshop...what is that exactly? It will be nice if you make a YouTube video on that to show it in action.

**Comment by mydockfinder** [comment]
现在的steam版本已经增加了切换图标的主题，后面的版本也会增加切换dock背景皮肤的功能，那些皮肤以后都会在steam创意工坊里面上传，订阅后就能切换了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月1日(星期六) 晚上9:23
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] MyDock -auto start at boot- not working! (Issue #318)






感谢你的快速反应，伙计。
在我之前的一张票中，你提到了创意工作坊……那到底是什么？这将是很好的，如果你做一个 YouTube 上的视频，以显示它在行动。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人. 
***@***.***与&gt;

**Comment by onlytanmoy** [comment]
ok got you, thanks for the clarification. I will wait for the MS Store version of MyDock to be available in few months to purchase it.

**Comment by grafikartes** [comment]
Hello, I just installed it and everything is fine, but the start menu does not open, has anyone had this problem?
