### ISSUE TITLE
Request: Support for AIMP on control center menu and current playback issue.

### ISSUE THREAD

**Issue by TRINCETT** [mydockfinder/mydockfinder#376]
Hello, I have been using MyDockFinder and one of the things that I have been waiting for to be implemented since the beginning is the support for aimp in the control center menu, apart from that when it is playing various things like music on spotify and a video from youtube it is very difficult to choose what you want to pause, having to enter the app to pause it, I don't know if that can be solved but it is somewhat annoying.
![Untitled](https://user-images.githubusercontent.com/93570862/166828504-ac7a3ee1-01e1-4ff2-bf40-48dbd43ac721.png)
As in this example, I am playing music on youtube and spotify, but I would like to pause the youtube one and I can't since the control center only shows 1 of the 2
![Untitled2](https://user-images.githubusercontent.com/93570862/166829144-cc3db3eb-47a1-4ed9-90ef-d6155361ad32.png)

**Comment by mydockfinder** [comment]
下个版本myfinder就是打算适配这些没有适配系统媒体控制的播放器，不过播放暂停状态不能正确识别，只能是点击一下暂停点击播放，上一曲下一曲可以点击




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 凌晨5:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Request: Support for AIMP on control center menu and current playback issue. (Issue #376)





 
Hello, I have been using MyDockFinder and one of the things that I have been waiting for to be implemented since the beginning is the support for aimp in the control center menu, apart from that when it is playing various things like music on spotify and a video from youtube it is very difficult to choose what you want to pause, having to enter the app to pause it, I don't know if that can be solved but it is somewhat annoying.
 
 As in this example, I am playing music on youtube and spotify, but I would like to pause the youtube one and I can't since the control center only shows 1 of the 2

**Comment by TRINCETT** [comment]
I commented this more than a month ago and  aimp is still not recognized by mydockfinder 😭 
![image](https://user-images.githubusercontent.com/93570862/180381178-a7d4d11c-29ec-4580-9909-d013f7af7fc9.png)

**Comment by mydockfinder** [comment]
so so so so sorry，我忘记了。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月22日(星期五) 下午2:50
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Request: Support for AIMP on control center menu and current playback issue. (Issue #376)






我在一个多月前发表了评论，但 a imp 仍然无法被 my dock finder 识别😭

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
你收到这个是因为你评论了。留言 ID ***@***.***与&gt;

**Comment by TRINCETT** [comment]
So this time its gonna be added? 😢

**Comment by mydockfinder** [comment]
已经添加了，下次更新就有了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月24日(星期天) 上午8:06
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Request: Support for AIMP on control center menu and current playback issue. (Issue #376)





 
So this time its gonna be added? 😢
 
&mdash;
