### ISSUE TITLE
快捷启动功能

### ISSUE THREAD

**Issue by xiaozhinian-g** [mydockfinder/mydockfinder#471]
请问有计划做个类似 win10的磁贴功能吗？

**Comment by mydockfinder** [comment]
这有点重复造轮子啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月10日(星期六) 下午4:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471)





 
请问有计划做个类似 win10的磁贴功能吗？

**Comment by xiaozhinian-g** [comment]
> 这有点重复造轮子啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月10日(星期六) 下午4:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471) 请问有计划做个类似 win10的磁贴功能吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

......
看了启动栏，不能设置图标大小，不能分块排版，放入文件夹的程序要点几次才能打开.......
升级win11后太怀念磁贴功能了，各种软件排版一目了然

**Comment by mydockfinder** [comment]
emmmmmmm
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月10日(星期六) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471)





  
这有点重复造轮子啊
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月10日(星期六) 下午4:28 收件人: @.&gt;; 抄送: @.&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471) 请问有计划做个类似 win10的磁贴功能吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
......
 看了启动栏，不能设置图标大小，不能分块排版，放入文件夹的程序要点几次才能打开.......
 升级win11后太怀念磁贴功能了，各种软件排版一目了然

**Comment by xiaozhinian-g** [comment]
> emmmmmmm &nbsp; №じ&nbsp;尐乄鈊~→☆ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月10日(星期六) 晚上9:12 收件人: ***@***.***&gt;; 抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471) 这有点重复造轮子啊 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年12月10日(星期六) 下午4:28 收件人: @.&gt;; 抄送: @.&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471) 请问有计划做个类似 win10的磁贴功能吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; ...... 看了启动栏，不能设置图标大小，不能分块排版，放入文件夹的程序要点几次才能打开....... 升级win11后太怀念磁贴功能了，各种软件排版一目了然 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

刚才在steam 下载的，发现火绒的图标不显示（顶部和底部都不显示），其他软件都正常
系统是win 11 ，22H1 ，22000.1219

**Comment by mydockfinder** [comment]
重启资源管理器就出来了，或者开机启动也能出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月10日(星期六) 晚上10:01
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471)





  
emmmmmmm   №じ 尐乄鈊~→☆ @.***  
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2022年12月10日(星期六) 晚上9:12 收件人: @.&gt;; 抄送: "№じ @.&gt;; @.&gt;; 主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471) 这有点重复造轮子啊 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2022年12月10日(星期六) 下午4:28 收件人: @.&gt;; 抄送: @.&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 快捷启动功能 (Issue #471) 请问有计划做个类似 win10的磁贴功能吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; ...... 看了启动栏，不能设置图标大小，不能分块排版，放入文件夹的程序要点几次才能打开....... 升级win11后太怀念磁贴功能了，各种软件排版一目了然 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
刚才在steam 下载的，发现火绒的图标不显示（顶部和底部都不显示），其他软件都正常
 系统是win 11 ，22H1 ，22000.1219
 
&mdash;
