### ISSUE TITLE
Dock_64.exe was reported as a threat by Windows Defender.

### ISSUE THREAD

**Issue by creamycd** [mydockfinder/mydockfinder#540]
Windows version: Windows 11 Enterprise 22621.1992
MyDockFinder version: Steam, Game Build ID 11658623

My MyDockFinder's `dock_64.exe`  was reported as a Threat by Windows Defender Antivirus.
The reason was finding a "Trojan:Win32/Randet.A!plock", and has been quarantined.
This issue happened when I rebooted my laptop.
The screenshot of Windows Defender is provided below, but it's written in Chinese.
If any additional log, screenshot, etc. ps needed, please tell me to provide.

![图片](https://github.com/mydockfinder/mydockfinder-for-Win10-Win11/assets/127870305/97e0c822-05a3-4a99-850f-0e552e9850c0)

**Comment by creamycd** [comment]
After 2 reboots, it works...
Sorry.

**Comment by mydockfinder** [comment]
道理我都懂为啥你用的英文
WD狠起来系统文件都报毒，没事基操勿6




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月14日(星期五) 中午12:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Dock_64.exe was reported as a threat by Windows Defender. (Issue #540)





 
Windows version: Windows 11 Enterprise 22621.1992
 MyDockFinder version: Steam, Game Build ID 11658623
 
My MyDockFinder's dock_64.exe  was reported as a Threat by Windows Defender Antivirus.
 The reason was finding a "Trojan:Win32/Randet.A!plock", and has been quarantined.
 This issue happened when I rebooted my laptop.
 The screenshot of Windows Defender is provided below, but it's written in Chinese.
 If any additional log, screenshot, etc. ps needed, please tell me to provide.

**Comment by creamycd** [comment]
……
大概是这两天写英文上头了，没想那么多，而且GitHub英文用户多…（汗）
确实，wd…不过当时也没想那么多，毕竟那可是wdಥ⁠‿⁠ಥ

________________________________
