### ISSUE TITLE
[issue][1.9.9.9] The dock icon progress bar is adapted to the system media control progress function for itune

### ISSUE THREAD

**Issue by linitfor** [mydockfinder/mydockfinder#707]
The dock icon progress bar is adapted to the system media control progress function current not support windows itune.

Windows itune website
[Windows itune](https://apps.microsoft.com/detail/9pb2mz1zmb1s?rtc=1&hl=zh-tw&gl=TW)

**Comment by mydockfinder** [comment]
That's because iTunes doesn't support the system's media control, so there's no way to display the progress




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月18日(星期四) 中午11:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] [issue][1.9.9.9] The dock icon progress bar is adapted to the system media control progress function for itune (Issue #707)














 
The dock icon progress bar is adapted to the system media control progress function current not support windows itune.
 
Windows itune website
 Windows itune

**Comment by linitfor** [comment]
OK ~ Got it !!
