### ISSUE TITLE
Can't focus app on a different desktop

### ISSUE THREAD

**Issue by elkhaligy** [mydockfinder/mydockfinder#743]
Clicking on an app's icon that exist in a different desktop doesn't do anything, the expected behavior is to switch to that desktop where the app window in there.

https://github.com/user-attachments/assets/c9672b1a-0187-4334-9c73-07a1071f7db6

**Comment by mydockfinder** [comment]
emmmm, it shouldn't be completely fixed, I'll fix it again




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月18日(星期三) 上午7:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Can&#39;t focus app on a different desktop (Issue #743)














 
Clicking on an app's icon that exist in a different desktop doesn't do anything, the expected behavior is to switch to that desktop where the app window in there.
 
https://github.com/user-attachments/assets/c9672b1a-0187-4334-9c73-07a1071f7db6

**Comment by elkhaligy** [comment]
It works only if this option is set on "On all desktops"

![image](https://github.com/user-attachments/assets/2f858101-f6fb-4a83-914a-33041dad283f)

**Comment by elkhaligy** [comment]
Fixed in the latest update, Thank you.
