### ISSUE TITLE
Folder contents thumbnails loading optimization

### ISSUE THREAD

**Issue by elkhaligy** [mydockfinder/mydockfinder#752]
Each time, the folder contents seems to be loading which is annoying.

https://github.com/user-attachments/assets/96310aa9-23a3-4705-b808-30f0fb6be0e7

**Comment by mydockfinder** [comment]
Yes, if the cache increases the usage of video memory, and the system will automatically clean up the video memory after not using it for a long time, and it will crash when you use it again




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月16日(星期三) 中午11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Folder contents thumbnails loading optimization (Issue #752)














 
Each time, the folder contents seems to be loading which is annoying.
 
https://github.com/user-attachments/assets/96310aa9-23a3-4705-b808-30f0fb6be0e7

**Comment by elkhaligy** [comment]
> Yes, if the cache increases the usage of video memory, and the system will automatically clean up the video memory after not using it for a long time, and it will crash when you use it again
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年10月16日(星期三) 中午11:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] Folder contents thumbnails loading optimization (Issue #752) Each time, the folder contents seems to be loading which is annoying. https://github.com/user-attachments/assets/96310aa9-23a3-4705-b808-30f0fb6be0e7 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

It happens on my PC too with 6 GB VRAM

**Comment by mydockfinder** [comment]
The point is not the amount of video memory, but the system will clean up the video memory after a long time.
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月16日(星期三) 中午11:53
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder contents thumbnails loading optimization (Issue #752)














  
Yes, if the cache increases the usage of video memory, and the system will automatically clean up the video memory after not using it for a long time, and it will crash when you use it again
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年10月16日(星期三) 中午11:41 收件人: @.&gt;; 抄送: @.&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] Folder contents thumbnails loading optimization (Issue #752) Each time, the folder contents seems to be loading which is annoying. https://github.com/user-attachments/assets/96310aa9-23a3-4705-b808-30f0fb6be0e7 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
It happens on my PC too with 6 GB VRAM

**Comment by elkhaligy** [comment]
Oh okay so is there a workaround to fix that behavior?

**Comment by mydockfinder** [comment]
Theoretically, there must be, I'll think again, or I'll ask the AI
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月16日(星期三) 中午11:58
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Folder contents thumbnails loading optimization (Issue #752)















好吧，那有什么变通方法可以纠正这种行为吗？

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by elkhaligy** [comment]
Great, hope you find a solution.

**Comment by elkhaligy** [comment]
Solved on latest update, Ty.
