### ISSUE TITLE
Dock changes size on hover if "Distance between icons" is set to 1 or above

### ISSUE THREAD

**Issue by sabretou** [mydockfinder/mydockfinder#759]
https://github.com/user-attachments/assets/c7816851-b115-40da-a8f7-d08df2934a30

I am using only the dock, with Icon effect set to Illumination, position top, and Dock Display Mode set to "Display only on the desktop". Happy to share more settings are required. The issue persists with Icon Effect set to "None".

When I set the distance between icons to any figure other than 0, and then hover my mouse over the dock, the dock seems to compress itself a bit than what it was actually set to. Even if the value is set to 0, it seems to slightly reposition itself on hover.

**Comment by mydockfinder** [comment]
That's true, it's fixed in the next version




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月25日(星期五) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Dock changes size on hover if &quot;Distance between icons&quot; is set to 1 or above (Issue #759)














 
https://github.com/user-attachments/assets/c7816851-b115-40da-a8f7-d08df2934a30
 
I am using only the dock, with Icon effect set to Illumination, position top, and Dock Display Mode set to "Display only on the desktop". Happy to share more settings are required. The issue persists with Icon Effect set to "None".
 
When I set the distance between icons to any figure other than 0, and then hover my mouse over the dock, the dock seems to compress itself a bit than what it was actually set to. Even if the value is set to 0, it seems to slightly reposition itself on hover.

**Comment by sabretou** [comment]
Thank you! I look forward to it.
