### ISSUE TITLE
Dock keeps blinking after clicking on "Show Desktop", if set to "Display only on the desktop"

### ISSUE THREAD

**Issue by sabretou** [mydockfinder/mydockfinder#760]
https://github.com/user-attachments/assets/8d1366b6-9ded-4dda-817f-861024fc2841

I am using only the dock. When I set it to "Display only on the desktop" and then click on Show Desktop (far right corner of the taskbar), or press Win + D, the dock keeps blinking intermittently.

The blinking stops if I restore any program, or right-click anywhere.

This does not occur if "Dock display mode" is set to any other value.

**Comment by mydockfinder** [comment]
There's really no way to fix this.,Because WIN+D or display desktop is forced by the system to minimize all windows.,If you can't minimize the window like dock or finder, this kind of window will let him hide behind the system desktop window.,It's been flashing, in fact, it's detected that it's hidden to the desktop.,The code makes the dock show back to the front.,But the system will force it to hide behind the desktop.,Finally, when you click on other windows, this mechanism will end and won't flash.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月25日(星期五) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] Dock keeps blinking after clicking on &quot;Show Desktop&quot;, if set to &quot;Display only on the desktop&quot; (Issue #760)














 
https://github.com/user-attachments/assets/8d1366b6-9ded-4dda-817f-861024fc2841
 
I am using only the dock. When I set it to "Display only on the desktop" and then click on Show Desktop (far right corner of the taskbar), or press Win + D, the dock keeps blinking intermittently.
 
The blinking stops if I restore any program, or right-click anywhere.
 
This does not occur if "Dock display mode" is set to any other value.

**Comment by sabretou** [comment]
Thank you, I understand this cannot be fixed.

Would I be mistaken to think that this is unique to Windows 11 24H2? The dock app I was using previous to this also started getting hidden with Win + D after I updated to 24H2, whereas it worked fine before that.

**Comment by mydockfinder** [comment]
Not really, because most people still need dock when WIN+D
&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月25日(星期五) 下午4:43
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Dock keeps blinking after clicking on &quot;Show Desktop&quot;, if set to &quot;Display only on the desktop&quot; (Issue #760)














 
Thank you, I understand this cannot be fixed.
 
Would I be mistaken to think that this is unique to Windows 11 24H2? The dock app I was using previous to this also started getting hidden with Win + D after I updated to 24H2, whereas it worked fine before that.

**Comment by sabretou** [comment]
Thank you! I understand.

**Comment by sabretou** [comment]
Interesting, this behaviour has stopped entirely. I imagine the latest Windows update has fixed it. Now if I press Win + D, I briefly see the dock disappear, but it reappears almost immediately and does not blink any more.

**Comment by mydockfinder** [comment]
This phenomenon is called metaphysics in China
It's like a supernatural




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月26日(星期六) 晚上7:18
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Dock keeps blinking after clicking on &quot;Show Desktop&quot;, if set to &quot;Display only on the desktop&quot; (Issue #760)





 
Interesting, this behaviour has stopped entirely. I imagine the latest Windows update has fixed it. Now if I press Win + D, I briefly see the dock disappear, but it reappears almost immediately and does not blink any more.
 
&mdash;
