### ISSUE TITLE
希望状态栏歌词适配MusicPlayer2

### ISSUE THREAD

**Issue by Ign1x** [mydockfinder/mydockfinder#807]
播放器项目地址：https://github.com/zhongyang219/MusicPlayer2

**Comment by mydockfinder** [comment]
已经适配了啊，有的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月28日(星期六) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [mydockfinder/mydockfinder-for-Win10-Win11] 希望状态栏歌词适配MusicPlayer2 (Issue #807)














 
播放器项目地址：https://github.com/zhongyang219/MusicPlayer2

**Comment by Ign1x** [comment]
> 已经适配了啊，有的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年12月28日(星期六) 下午2:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 希望状态栏歌词适配MusicPlayer2 (Issue #807) 播放器项目地址：https://github.com/zhongyang219/MusicPlayer2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
还真有重启了程序就出现了，但是好怪，字好小
![image](https://github.com/user-attachments/assets/10e58e7b-dd49-468c-b89e-464428e1c4c9)

**Comment by mydockfinder** [comment]
把桌面歌词的窗口调整高度窄一些就可以了


&nbsp;


№じ&nbsp;尐乄鈊~→☆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月28日(星期六) 晚上9:26
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] 希望状态栏歌词适配MusicPlayer2 (Issue #807)














  
已经适配了啊，有的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年12月28日(星期六) 下午2:43 收件人: @.&gt;; 抄送: @.&gt;; 主题: [mydockfinder/mydockfinder-for-Win10-Win11] 希望状态栏歌词适配MusicPlayer2 (Issue #807) 播放器项目地址：https://github.com/zhongyang219/MusicPlayer2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
 还真有重启了程序就出现了，但是好怪，字好小
 image.png (view on web)
